spring: 
 application: 
  name: gateway-zuul # 应用名
 #cloud: #启动负载均衡的重试机制，默认false
    #loadbalancer: 
      #retry: 
        #enabled: true
  
 
server: 
 port: 8768 #Zuul Server的端口号  

      

eureka: 
 client: 
  service-url: 
   defaultZone: http://localhost:8761/eureka 


zuul: 
  routes:
    forest-api: 
      path: /forest/**
      service-id: forest-api 
  TokenFilter: #禁用TokenFilter过滤器
    pre: 
       disable: true
  
