spring:
  application:
    # 服务名称
    name: forest-api
  #oracle database settings
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@192.168.1.115:1521:orcl
    username: jeesite
    password: jeesite
    driverClassName: oracle.jdbc.driver.OracleDriver 
    #mysql database setting
    #platform: mysql
    #url: jdbc:mysql://localhost:3306/forest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #username: root
    #password: 123456
    #driverClassName: com.mysql.jdbc.Driver
    # 阿里巴巴Druid数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #初始化时建立物理连接的个数
      min-idle: 5 #最小连接池数量
      max-active: 20 #最大连接池数量 maxIdle已经不再使用
      max-wait: 60000 #获取连接时最大等待时间，单位毫秒
      test-while-idle: true #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      time-between-eviction-runs-millis: 60000 #既作为检测的间隔时间又作为testWhileIdel执行的依据
      min-evictable-idle-time-millis: 30000 #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      validation-query: select 1 from dual #用来检测连接是否有效的sql 必须是一个查询语句  #mysql中为 select 'x' #oracle中为 select 1 from dual
      test-on-borrow: false  #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true      
      test-on-return: false #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true     
      exception-sorte: true #当数据库抛出不可恢复的异常时,抛弃该连接 
      #pool-prepared-statements: true  #是否缓存preparedStatement,mysql5.5+建议开启  
      max-pool-prepared-statement-per-connection-size: 20  #当值大于0时poolPreparedStatements会自动修改为true    
      filters: stat,wall  #配置扩展插件 
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      use-global-data-source-stat: true  #合并多个DruidDataSource的监控数据

mybatis:
  mapperLocations: classpath:/mappings/**/*.xml
  type-aliases-package: com.forest.api.entity
  #开启自动驼峰命名规则（camel case）映射
  configuration:
    map-underscore-to-camel-case: true
# 服务注册中心
eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 该配置指示eureka客户端需要向eureka服务器发送心跳的频率  (Spring Cloud默认该配置是 30s)
    lease-renewal-interval-in-seconds: 10
    # 该配置指示eureka服务器在接收到最后一个心跳之后等待的时间，然后才能从列表中删除此实例 (Spring Cloud默认该配置是 90s)
    lease-expiration-duration-in-seconds: 30
server:
  port: 8081

  tomcat:
    max-http-post-size: 1
    uri-encoding: UTF-8
  #开启https
  #ssl:
    #key-store: classpath:keystore.p12
    #key-store-password: 123456
    #key-store-type: PKCS12
    #key-alias: tomcat

#打开feign-hystrix
feign: 
  hystrix: 
    enabled: true

ribbon:
  ReadTimeout: 10000 #处理超时时间 默认5秒
  ConnectTimeout: 10000 #连接超时时间 默认2秒
  #MaxAutoRetries: 0
  #MaxAutoRetriesNextServer: 1
 
 
#hystrix 配置
hystrix:
  command: 
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 12000 #断路切换超时

management: 
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint: 
      health:
        show-details: ALWAYS
        
# 配置info信息
info: 
  app.name: forest-api
  company.name: www.forest.com
  build.artifactId: $project.artifactId$

logging:
  config: classpath:log4j2.yml 