server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # 每隔10s扫描服务列表，移除失效服务
    eviction-interval-timer-in-ms: 10000
    # 该配置可以移除这种自我保护机制，防止失效的服务也被一直访问 (Spring Cloud默认该配置是 true)
    enable-self-preservation: false

