server:
  port: 7010

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/rit/spring-cloud
          search-paths: config-repository
          username: 646884827@qq.com  
          password: guoshilin1989
      label: master